
MEM_SIZE = 65536

C_DEPS = \
	../InterruptController/InterruptController.c \
	../UART/UART-buffered.c \
	../Timer/Timer.c \
	../SegmentDisplay/SegmentDisplay.c \
	../Platform/Platform.c

C_FLAGS_USER = -Os

all: FullDemo.hex

include ../../../scripts/Virgule.make
