
MEM_SIZE = 65536

C_DEPS = \
	../InterruptController/InterruptController.c \
	../UART/UART-buffered.c \
	../Platform/Platform.c

C_FLAGS_USER = -Os

all: Hello.hex

include ../../../scripts/Virgule.make
