
MEM_SIZE = 65536

all: Loader_pkg.vhd

C_DEPS = \
	../InterruptController/InterruptController.c \
	../UART/UART-basic.c \
	../Memory/Memory.c

C_FLAGS_USER = -Os

include ../../../scripts/Virgule.make
